#include "Version.h"

const char* APP_NAME = PROJECT_NAME;
const char* APP_COMPANY_NAME = PROJECT_COMPANY_NAME;
const char* APP_VERSION =
    STRINGIFY(PROJECT_VERSION_MAJOR) "."
    STRINGIFY(PROJECT_VERSION_MINOR) "."
    STRINGIFY(PROJECT_VERSION_PATCH);